### ISSUE TITLE
[Bug] PC Falls Asleep with Move Mouse Active / Not staying active on Teams

### ISSUE THREAD

**Issue by cavazoshj** [sw3103/movemouse#36]
PC keeps falling asleep while using Move Mouse. Defeats the purpose of staying active. I use task scheduler to start/stop the program (schedules don't seem to work for me all the time) and every time I step away and come back, I notice my monitors are off and the PC is asleep. Would prefer not to change power settings.

**Comment by Belabacsi** [comment]
Same for me :-( I have tried to change a lot of configuration parameters, but I always got the same results. As soon as the first timer expires, it stops working.

![2022-11-12_16-40-52_powershell](https://user-images.githubusercontent.com/31376636/201482191-860a736f-c533-49a3-a88c-9e6b78b87b10.png)

**Comment by sw3103** [comment]
Hi,

Please could you both post/send your Settings.xml files?

%AppData%\Ellanet\Move Mouse\Settings.xml

**Comment by cavazoshj** [comment]
I am trying to only have it active between 8 to 4, Monday through Friday and used the example blackout provided. Move Mouse appears to be active and work for a short period of time but then stops mimicking mouse movements.

`<?xml version="1.0" encoding="utf-8"?>
<Settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <LowerInterval>1</LowerInterval>
  <UpperInterval>60</UpperInterval>
  <RandomInterval>false</RandomInterval>
  <AutoPause>false</AutoPause>
  <AutoResume>true</AutoResume>
  <AutoResumeSeconds>30</AutoResumeSeconds>
  <EnableLogging>false</EnableLogging>
  <TopmostWhenRunning>false</TopmostWhenRunning>
  <HideFromTaskbar>false</HideFromTaskbar>
  <HideFromAltTab>false</HideFromAltTab>
  <HideMainWindow>true</HideMainWindow>
  <HideSystemTrayIcon>false</HideSystemTrayIcon>
  <LaunchAtLogon>false</LaunchAtLogon>
  <StartAtLaunch>true</StartAtLaunch>
  <MoveMouseHasBeenClicked>true</MoveMouseHasBeenClicked>
  <ActionsHaveBeenClicked>false</ActionsHaveBeenClicked>
  <OverrideWindowTitle>false</OverrideWindowTitle>
  <OverrideIcon>false</OverrideIcon>
  <RunningVolume>30</RunningVolume>
  <AdjustRunningVolume>false</AdjustRunningVolume>
  <MinimiseOnStop>false</MinimiseOnStop>
  <PreventScreenBurn>false</PreventScreenBurn>
  <ActiveWhenLocked>false</ActiveWhenLocked>
  <ShowMoveMouseStatus>false</ShowMoveMouseStatus>
  <DisableButtonAnimation>false</DisableButtonAnimation>
  <StandWithUkraine>false</StandWithUkraine>
  <PauseOnBattery>false</PauseOnBattery>
  <LogLevel>Verbose</LogLevel>
  <ShowSystemTrayNotifications>false</ShowSystemTrayNotifications>
  <Actions>
    <MoveMouseCursorAction>
      <Id>7e1ef0c1-972a-487f-ac5a-a35f34fd4d92</Id>
      <IsEnabled>true</IsEnabled>
      <Repeat>true</Repeat>
      <Trigger>Interval</Trigger>
      <Distance>3</Distance>
      <Direction>None</Direction>
      <Speed>Normal</Speed>
      <Delay>5</Delay>
    </MoveMouseCursorAction>
  </Actions>
  <Schedules />
  <Blackouts>
    <Blackout>
      <Id>d794209d-7c06-44b2-b690-2e0ffc024263</Id>
      <Monday>true</Monday>
      <Tuesday>true</Tuesday>
      <Wednesday>true</Wednesday>
      <Thursday>true</Thursday>
      <Friday>true</Friday>
      <Saturday>true</Saturday>
      <Sunday>true</Sunday>
      <Time>16:00:00</Time>
      <Duration>14:00:00</Duration>
    </Blackout>
    <Blackout>
      <Id>1fd7a1cf-6618-4474-a8b3-5dbe9cbda5c0</Id>
      <Monday>false</Monday>
      <Tuesday>false</Tuesday>
      <Wednesday>false</Wednesday>
      <Thursday>false</Thursday>
      <Friday>false</Friday>
      <Saturday>false</Saturday>
      <Sunday>true</Sunday>
      <Time>08:00:00</Time>
      <Duration>10:00:00</Duration>
    </Blackout>
  </Blackouts>
</Settings>`

**Comment by sw3103** [comment]
@cavazoshj please enable Logging and email it to me when you next see the issue, along with the time the issue occurred.

**Comment by Belabacsi** [comment]
> Hi,
> 
> Please could you both post/send your Settings.xml files?
> 
> %AppData%\Ellanet\Move Mouse\Settings.xml

Dear Steve ! I have sent an e-mail to You with my configuration and log files attached.

**Comment by cavazoshj** [comment]
> 

Logs have been emailed after observing Teams set status to away while logging shows Move Mouse is active.

**Comment by sw3103** [comment]
> > Hi,
> > Please could you both post/send your Settings.xml files?
> > %AppData%\Ellanet\Move Mouse\Settings.xml
> 
> Dear Steve ! I have sent an e-mail to You with my configuration and log files attached.

Hi Bela,

I can see the issue after reviewing your config file. You have a single Move Mouse Cursor Action, which has the Trigger set to Start.

`
...
  <Actions>
    <MoveMouseCursorAction>
      <Id>a98f011c-e93e-427d-b6a8-5031f4a2934a</Id>
      <Name>Default</Name>
      <IsEnabled>true</IsEnabled>
      <Repeat>true</Repeat>
      <Trigger>Start</Trigger>
      <Distance>5</Distance>
      <Direction>Square</Direction>
      <Speed>Normal</Speed>
      <Delay>5</Delay>
    </MoveMouseCursorAction>
  </Actions>
...
`

This means that when Move Mouse starts, it will execute this Action and then automatically stop as you have no Actions with a Trigger that is configured for Interval. Try changing the Trigger on this Action to Interval and see if that resolves your issue.

**Comment by sw3103** [comment]
> > @cavazoshj please enable Logging and email it to me when you next see the issue, along with the time the issue occurred.
> 
> Logs have been emailed after observing Teams set status to away while logging shows Move Mouse is active.

Thanks for the logs @cavazoshj. I'll reply in this thread for the benefit of any future observers.

I can see from the logs that your system idle time is being successfully reset each time Move Mouse performs your Move Mouse Cursor Action (this is the time span after each _autoPauseTimer_Elapsed):

`2022-11-14 08:51:00.018	[DBG]	_autoPauseTimer_Elapsed	00:00:29.5780000
2022-11-14 08:51:00.268	[DBG]	_autoPauseTimer_Elapsed	00:00:29.8280000
2022-11-14 08:51:00.441	[INF]	PerformActions	Interval
2022-11-14 08:51:00.441	[INF]	PerformActions	_firstPass = False
2022-11-14 08:51:00.441	[DBG]	BlackoutIsActive	False
2022-11-14 08:51:00.441	[INF]	CurrentState	Executing
2022-11-14 08:51:00.441	[DBG]	OnMouseStateChanged	Executing
2022-11-14 08:51:00.441	[DBG]	_vm_MouseStateChanged	Executing
2022-11-14 08:51:00.441	[DBG]	StopAutoPauseTimer	
2022-11-14 08:51:00.441	[INF]	Execute	Name =  | Distance = 3 | Direction = None | Speed = Normal | Delay = 5 | Trigger = Interval | Repeat = True
2022-11-14 08:51:00.441	[INF]	Start	
2022-11-14 08:51:00.441	[DBG]	BlackoutIsActive	False
2022-11-14 08:51:00.441	[DBG]	StopAutoResumeTimer	
2022-11-14 08:51:00.441	[INF]	PerformActions	Start
2022-11-14 08:51:00.441	[INF]	PerformActions	_firstPass = False
2022-11-14 08:51:00.441	[INF]	ExecutionTime	08:51:30
2022-11-14 08:51:00.441	[INF]	CurrentState	Running
2022-11-14 08:51:00.441	[DBG]	OnMouseStateChanged	Running
2022-11-14 08:51:00.441	[DBG]	_vm_MouseStateChanged	Running
2022-11-14 08:51:00.441	[DBG]	StopBlackoutTimer	
2022-11-14 08:51:00.441	[DBG]	StartAutoPauseTimer	
2022-11-14 08:51:00.441	[DBG]	StopAutoPauseTimer	
2022-11-14 08:51:00.691	[DBG]	_autoPauseTimer_Elapsed	00:00:00.2500000
2022-11-14 08:51:00.942	[DBG]	_autoPauseTimer_Elapsed	00:00:00.5000000
2022-11-14 08:51:01.193	[DBG]	_autoPauseTimer_Elapsed	00:00:00.7500000
2022-11-14 08:51:01.444	[DBG]	_autoPauseTimer_Elapsed	00:00:01`

I'm pretty sure your issue is to do with Teams itself, which doesn't seem to be easily fooled by routine mouse movements. You also mentioned in your mail that your were using the web version of Teams, which I don't personally have much experience with, but I would imagine will behave much the same as the client version.

Here is my suggestion - add the following Actions:

- Active Application Action which will activate your web browser that you use for Teams. This should be configured with a Trigger set to Start.
- Multiple (5 - 10) Move Mouse Cursor Actions. Each one should have a different Distance (min 50), Direction set to Random, a different Speed and a Trigger set to Interval.

Hopefully with the random Directions and Speeds this will be enough to trick Teams.

**Comment by cavazoshj** [comment]
After adding the additional actions and watching for a couple days, the issue seems to have been user error and teams' advance away detection. Thanks, Steve. Great application. Closing issue.

**Comment by Belabacsi** [comment]
> > > Hi,
> > > Please could you both post/send your Settings.xml files?
> > > %AppData%\Ellanet\Move Mouse\Settings.xml
> > 
> > 
> > Dear Steve ! I have sent an e-mail to You with my configuration and log files attached.
> 
> Hi Bela,
> 
> I can see the issue after reviewing your config file. You have a single Move Mouse Cursor Action, which has the Trigger set to Start.
> 
> `
> 
> ```
> <MoveMouseCursorAction>
> 
>   <Id>a98f011c-e93e-427d-b6a8-5031f4a2934a</Id>
> 
>   <Name>Default</Name>
> 
>   <IsEnabled>true</IsEnabled>
> 
>   <Repeat>true</Repeat>
> 
>   <Trigger>Start</Trigger>
> 
>   <Distance>5</Distance>
> 
>   <Direction>Square</Direction>
> 
>   <Speed>Normal</Speed>
> 
>   <Delay>5</Delay>
> 
> </MoveMouseCursorAction>
> ```
> 
> `
> 
> This means that when Move Mouse starts, it will execute this Action and then automatically stop as you have no Actions with a Trigger that is configured for Interval. Try changing the Trigger on this Action to Interval and see if that resolves your issue.

Dear Steve ! Thank You very much for the feedback, this solves my issue.
