### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by ealipio** [sw3103/movemouse#54]
Hey guys, is there a chance to have support for mac? do you guys know a similar application for mac? thanks!

**Comment by sw3103** [comment]
Hi,

I am afraid that due to the underlying APIs which only exist on Windows, it won't be possible to port this over to macOS.

Being a Mac user myself however - I can highly recommend the following application which I use to keep my sessions alive:

https://apps.apple.com/us/app/amphetamine/id937984704
